### ISSUE TITLE
Type 'FunctionComponent<IProps>' is not assignable to type '"input" | "select" | "textarea" | ComponentClass<FieldRenderProps<string, HTMLElement>, any> | FunctionComponent<FieldRenderProps<string, HTMLElement>> | undefined'

### ISSUE THREAD

**Issue by jags212** [final-form/react-final-form#687]
![ReactIssue_3](https://user-images.githubusercontent.com/30613381/69900681-8119d080-139c-11ea-90df-8c07a770b99a.JPG)
![ReactIssue_1](https://user-images.githubusercontent.com/30613381/69900683-8119d080-139c-11ea-8cfb-403c298330d4.JPG)
![ReactIssue_2](https://user-images.githubusercontent.com/30613381/69900684-81b26700-139c-11ea-8927-d9e5682fb301.JPG)

**Comment by streetwiseherc** [comment]
I see you're going through the "Reactivities" Udemy course by @TryCatchLearn also!?  :)

**Comment by streetwiseherc** [comment]
Another option, if you want to keep up with the latest version (6.3.3 today) is to change ```HTMLInputElement``` to ```any``` in the following code:

```
interface IProps
  extends FieldRenderProps<string, HTMLInputElement>,
    FormFieldProps {}

const TextInput: React.FC<IProps> = ({
```

I got this idea from the code samples/documentation that can be found here: https://codesandbox.io/s/strongly-typed-form-values-with-react-final-form-26jkd

**Comment by jags212** [comment]
Thank you @streetwiseherc

**Comment by nboltn** [comment]
wait why is this closed? I'm getting this same issue and prefer not to downgrade if there's no reason to.

**Comment by jags212** [comment]
@nboltn But downgrading the package did the trick.

**Comment by nboltn** [comment]
but the underlying issue has not been solved, this should remain open until then. downgrading is only a hot-fix. as street said, that version is over six months old.

**Comment by jags212** [comment]
May be you check with the below code sandbox Url for work-around : 

https://codesandbox.io/s/strongly-typed-form-values-with-react-final-form-26jkd

Let me know if it helps.

**Comment by Premashanth** [comment]
> I see you're going through the "Reactivities" Udemy course by @TryCatchLearn also!? :)
> 
> If you're looking for a **temporary workaround** to get past this and continue with the course, you can uninstall the "react-final-form" package and install the specific version that Neil used when he created the course.
> 
> ```
> cd client-app
> npm uninstall react-final-form
> npm install react-final-form@6.3.0
> ```
> 
> That seemed to work for me.
> 
> Note: Version 6.3.0 is about 6 months old, and version 6.3.1+ was released in the last 16 days.

Thanks buddy

**Comment by wesbw** [comment]
To solve this issue without downgrade;
in TextInput.tsx instead of using HTMLInputElement I used HTMLElement 

interface IProps extends FieldRenderProps<string, HTMLElement>

**Comment by medlotf** [comment]
@wesbw  replacing  with HTMLElement  will result an other error related to meta (in this exemple)

**Comment by wesbw** [comment]
@medlotf interesting, what is the error you faced? I tried it and it worked on my project. I just pushed it to github today at the end of section 10; https://github.com/wesbw/Reactivities

**Comment by sinalias** [comment]
> To solve this issue without downgrade;
> in TextInput.tsx instead of using HTMLInputElement I used HTMLElement
> 
> interface IProps extends FieldRenderProps<string, HTMLElement>

This works fine for me. I haven't any problem with the meta parameter that medlotf said.

**Comment by ghotir** [comment]
When you get to the DateInput there is another error, that downgrading didn't solve.  

The expected type comes from property 'component' which is declared here on type 'IntrinsicAttributes & FieldProps<string, HTMLInputElement>'

I can change 
extends FieldRenderProps<Date, HTMLInputElement>,

back to string, but that removes all the date stuff that it had going on.

**Comment by klodvik** [comment]
For the Date input one of the solutions is to specify the type of a value on the Final Form Field like:

<Field<Date>
                  name='date'
                  placeholder='Date'
                  value={activity.date}
                  component={DateInput}
                />

Hopefully this helps someone!

**Comment by EricZX26** [comment]
1. Replace HTMLInputElement with HTMLElement in any FieldRenderProps<,>
2. Remove   ...rest and {  ...rest} in DateInput component

**Comment by kyon12345** [comment]
> For the Date input one of the solutions is to specify the type of a value on the Final Form Field like:
> 
> ```
> <Field<Date>
> name='date'
> placeholder='Date'
> value={activity.date}
> component={DateInput}
> />
> ```
> 
> Hopefully this helps someone!

try to use FieldRenderProps<Date, HtmlElement> or  FieldRenderProps<any, any> 
in your child component

**Comment by jags212** [comment]
Recently i did a npm update and i see the attached compilation Issue coming up.
![image](https://user-images.githubusercontent.com/30613381/80677273-48f6f500-8ad6-11ea-9549-3b32a43a833b.png)

**Comment by Dariel90** [comment]
@jags212 Have you any answer to this?

**Comment by jags212** [comment]
> @jags212 Have you any answer to this?

I did re-install the previous version to resolve the issue.

**Comment by manjujeewa** [comment]
> Another option, if you want to keep up with the latest version (6.3.3) is to change `HTMLInputElement` to `any` in the following code:
> 
> ```
> interface IProps
>   extends FieldRenderProps<string, HTMLInputElement>,
>     FormFieldProps {}
> 
> const TextInput: React.FC<IProps> = ({  /* blah blah blah */
> ```
> 
> I got this idea from the code samples/documentation that can be found here: https://codesandbox.io/s/strongly-typed-form-values-with-react-final-form-26jkd
> 
> I can't comment on what has changed over the last 6 months, but I'm going to stick with version 6.3.0 which is the version the Udemy course was authored with. Generally, in today's world where things change quickly, it's best to use the package/library version numbers used when the course/book/post was authored.

This solution worked for me. Thanks

**Comment by deltics** [comment]
> For the Date input one of the solutions is to specify the type of a value on the Final Form Field like:
> 
> ```
> <Field<Date>
> name='date'
> placeholder='Date'
> value={activity.date}
> component={DateInput}
> />
> ```
> 
> Hopefully this helps someone!

Thank You!  Even using the exact versions of semantic-ui and final-form as specified in the course was not helping me until THIS refinement!!

**Comment by deltics** [comment]
Ok, reverting to the specific versions used in the course created a host of further problems for me, so I went back to using the latest versions of everything and trying to solve each problem properly.

So, using react-final-form@6.5.1 and semantic-ui-react@0.88.2, this is what I came up with:

On all the form components, removed the 2nd type param from the IProps declarations:

    interface IProps
        extends FieldRenderProps<string>, FormFieldProps {
    };

and for the DatePicker:

    interface IProps
        extends FieldRenderProps<Date>, FormFieldProps {
    };

No other changes were needed on the input components other than on the DatePicker.  In this case the `id` property had to be restructured explicitly (not as part of the `...rest` spread):

    const DateTimeInput: React.FC<IProps> = ({
                                             input,
                                             width,
                                             placeholder,
                                             meta: {
                                                 touched,
                                                 error
                                             },
                                             id,
                                             ...rest
                                         }) => 

which then is converted to the required string value as part of the DateTimePicker element props:

            <DateTimePicker id={id ? id.toString() : ''}
                            placeholder={placeholder}
                            value={input.value}
                            onChange={input.onChange}
                            {...rest}/>

Then finally, in the ActivityForm, provide the value type param on the Field element, as suggested by @kyon12345:

                                       <Field<Date> component={DateTimeInput}
                                              placeholder='Date'
                                              name='date'
                                              value={activity.date!}/>

Then after fixing all the date typing and formatting, the app once more ran without any console vomit!  (apart from some componentDidMount and componentWillReceiveProps warnings originating from the DateTimePicker and Calendar).

I hope this helps some people.

**Comment by freadam** [comment]
Any updates?

**Comment by milyas19** [comment]
I had a feeling that newer version of react-final-form will not work and it didn't work. Thank you for sharing the solution and command. Cheers 👍
