### ISSUE TITLE
engines in patch release 6.5.4 is a breaking compatibility change

### ISSUE THREAD

**Issue by zburke** [final-form/react-final-form#945]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

Patch release 6.5.4 of react-final-form contains breaking compatibility changes introduced in #943:
```
// package.json
// …
  "engines": {
    "node": "14"
  },
```
For users on node < 14 (node v12 is still in maintenance mode through mid-2022) or > 14 (node v16 is in active development), this is a breaking change. 

### What is the expected behavior?

Patch release should not contain breaking compatibility changes.

### Sandbox Link

Not relevant.

### What's your environment?

Node v12.22.2

### Other information

Relates to https://github.com/final-form/final-form/issues/434

**Comment by erikras** [comment]
Should be fixed in [`v6.5.5`](https://github.com/final-form/react-final-form/releases/tag/v6.5.5).

**Comment by zburke** [comment]
@erikras, sorry, that didn't do it. I still see [`engines` in the `react-final-form` `package.json`](https://github.com/final-form/react-final-form/blob/912515970056ed9a6b39b641080779bfc0fad9f5/package.json#L31-L33) in `v6.5.5`. Bumping `final-form` from `4.20.3` to `4.20.4` was necessary but not sufficient.

```
error react-final-form@6.5.5: The engine "node" is incompatible with this module. Expected version "14". Got "16.10.0"
error Found incompatible module.
```

**Comment by erikras** [comment]
Oops. Should _really_ be fixed in [`v6.5.6`](https://github.com/final-form/react-final-form/releases/tag/v6.5.6). 🤞
